sudo: required
language: generic

services:
  - docker

jobs:
  include:
    - stage: "Build and Test"
      before_script:
        - curl -fsSL https://goss.rocks/install | sudo sh
      script:
        - ./build-n-test.sh

notifications:
  webhooks:
    urls:
      - https://hub.docker.com/api/build/v1/source/e4f4be76-65f6-4bfc-b32e-c4fbd2b11421/trigger/f9f27771-eaa7-4413-8348-c3079893b048/call/
    on_success: always
    on_failure: never
    on_start: never
    on_cancel: never
    on_error: never
